version: '3.7'
services: 
    docker-fastapi:
        container_name: docker-fastapi
        build: 
            context: ./backend/
            dockerfile: Dockerfile
        links:
            - db
        environment:
            - MONGO_HOST=mongo_db 
            - MONGO_PORT=27107
            - MONGO_USERNAME=root
            - MONGO_PASSWORD=pass
        restart: always
    nginx:
        depends_on: 
            - docker-fastapi
        container_name: proxy-app
        build: 
            context: ./frontend/
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
    db:
        image: mongo:latest
        hostname: mongo_db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root 
            - MONGO_INITDB_ROOT_PASSWORD=pass
            
